remote_theme: pmarsceill/just-the-docs

title: Math
description: Materiais didáticos de estatística para dados conversacionais em educação — código Python executável, slides e referências.

favicon_ico: "/imgs/favicon.png"

aux_links:
  "Github":
    - "https://github.com/rodrigoprestesmachado/math"

footer_content: "Copyright &copy; 2026 <a href='https://rpmhub.dev'>RPM Hub</a>. Distributed by <a href='https://creativecommons.org/licenses/by/4.0/'>CC-BY-4.0 license</a>."
